### ISSUE TITLE
Termux-desktop

### ISSUE THREAD

**Issue by shim80** [suhan-paradkar/termux-wayland#33]
Teemux desktop (openbox based desktop) doesn't seem to work with XWayland.
I can launch xfce4 without any issues, but when I installed termux-desktop, there's no way to make it work with XWayland...
I was able to launch desktop anyway with the command "openbox-session", but there's no input and the screen freeze

Here's the termux log:
export XDG_RUNTIME_DIR=$TMPDIR

Xwayland :0 1> /dev/null &

env DISPLAY=:0 openbox-session
[1] 14142
The XKEYBOARD keymap compiler (xkbcomp) reports:
> Warning:          Unsupported maximum keycode 569, clipping.
>                   X11 cannot support keycodes above 255.
Errors from xkbcomp are not fatal to the X server
Obt-Message: Failed to open an Input Method
Openbox-Message: X server does not support locale.
Openbox-Message: Cannot set locale modifiers for the X server.
Not using O_TMPFILE
Failed to connect to session manager: Failed to connect to the session manager: SESSION_MANAGER environment variable not defined
notice: Parsing config file: /data/data/com.termux/files/home/.config/polybar/default/config.ini
warn: No monitor specified, using "XWAYLAND0"
warn: The config parameter 'settings.throttle-input-for' is deprecated, it will be removed in the future. Please remove it from your config

ERROR: openbox-xdg-autostart requires PyXDG to be installed

notice: pulseaudio: using default sink OpenSL_ES_sink
notice: Loaded font "Iosevka Nerd Font:size=10" (name=Iosevka, offset=3, file=/data/data/com.termux/files/home/.fonts/icons/iosevka-nerd-font.ttf)
notice: Loaded font "Iosevka Nerd Font:size=12" (name=Iosevka, offset=3, file=/data/data/com.termux/files/home/.fonts/icons/iosevka-nerd-font.ttf)
notice: Loaded font "Iosevka Nerd Font:size=20" (name=Iosevka, offset=5, file=/data/data/com.termux/files/home/.fonts/icons/iosevka-nerd-font.ttf)
Aug 09 16:41 : exception: Failed to bind to '127.0.0.1:6600'; Failed to bind socket: Address already in use
error: tray: Failed to put tray above 0x0e00001 in the stack (XCB_MATCH (8))

**Comment by suhan-paradkar** [comment]
> ERROR: openbox-xdg-autostart requires PyXDG to be installed

It already says that you have to install PyXDG...
try after

```bash
pip install PyXDG
```

**Comment by shim80** [comment]
> > ERROR: openbox-xdg-autostart requires PyXDG to be installed
> 
> It already says that you have to install PyXDG...
> try after
> 
> ```shell
> pip install PyXDG
> ```
I did that, there's no changes

**Comment by shim80** [comment]
Oh, that's work ! There's just some desktop glitches, but this is openbox related.

**Comment by suhan-paradkar** [comment]
Great👍👍
