### ISSUE TITLE
Add screen reseeding options 

### ISSUE THREAD

**Issue by Yisus7u7** [suhan-paradkar/termux-wayland#5]
Hello, it would be good to add the option that the screen can be resizar or adapts when detaching the keyboard from the cell phone, because it is very uncomfortable that the keyboard covers the entire screen, something I made similar to use a vnc client

**Comment by suhan-paradkar** [comment]
You mean The external keyboard??

**Comment by Yisus7u7** [comment]
> ¿Te refieres al teclado externo?

No

**Comment by suhan-paradkar** [comment]
So you want it to adjust screen height according to the keyboard toggle status??

**Comment by Yisus7u7** [comment]
> So you want it to adjust screen height according to the keyboard toggle status??

Yes!
